[package]
name = "timely_container"
version = "0.31.0"
description = "Container abstractions for Timely"
license = "MIT"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["columnar"]
columnar = ["dep:columnar", "dep:timely_bytes"]

[dependencies]
columnar = { workspace = true, optional = true }
timely_bytes = { path = "../bytes", version = "0.31", optional = true }
